// app/layout.tsx (fixed)
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { sourGummy, yellowtail } from "./lib/fonts";
import { auth } from "./lib/auth";
import { db } from "@/."; // adjust path if needed
import { headers } from "next/headers";
import { user } from "./lib/schema";
import { eq } from "drizzle-orm";
import { redirect } from "next/navigation";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${sourGummy.variable} ${yellowtail.variable} bg-white`}>{children}</body>
    </html >
  );
}
